/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFbiseAssetRouteImport } from './routes/api/public/fbise/asset'
import { Route as ApiPublicFbiseResultRouteImport } from './routes/api/public/fbise/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbiseAssetRoute = ApiPublicFbiseAssetRouteImport.update({
  id: '/api/public/fbise/asset',
  path: '/api/public/fbise/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbiseResultRoute = ApiPublicFbiseResultRouteImport.update({
  id: '/api/public/fbise/result',
  path: '/api/public/fbise/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/fbise/asset': typeof ApiPublicFbiseAssetRoute
  '/api/public/fbise/result': typeof ApiPublicFbiseResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/fbise/asset': typeof ApiPublicFbiseAssetRoute
  '/api/public/fbise/result': typeof ApiPublicFbiseResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/fbise/asset': typeof ApiPublicFbiseAssetRoute
  '/api/public/fbise/result': typeof ApiPublicFbiseResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/fbise/asset' | '/api/public/fbise/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/fbise/asset' | '/api/public/fbise/result'
  id: '__root__' | '/' | '/api/public/fbise/asset' | '/api/public/fbise/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicFbiseAssetRoute: typeof ApiPublicFbiseAssetRoute
  ApiPublicFbiseResultRoute: typeof ApiPublicFbiseResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fbise/asset': {
      id: '/api/public/fbise/asset'
      path: '/api/public/fbise/asset'
      fullPath: '/api/public/fbise/asset'
      preLoaderRoute: typeof ApiPublicFbiseAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fbise/result': {
      id: '/api/public/fbise/result'
      path: '/api/public/fbise/result'
      fullPath: '/api/public/fbise/result'
      preLoaderRoute: typeof ApiPublicFbiseResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicFbiseAssetRoute: ApiPublicFbiseAssetRoute,
  ApiPublicFbiseResultRoute: ApiPublicFbiseResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
